#!/bin/sh

bring() {
  git clone "https://github.com/extra-lists/$1"
  mv "$1/index.js" "$1.js"
  mv "$1/README.md" "$1.md"
  rm -rf "$1"
}

bring "indices-of"
bring "some"
bring "index-of"
bring "find-last-index"
bring "last"
bring "last-index-of"
bring "includes"
bring "find-index"
bring "join"
bring "find-last"
bring "middle"
bring "map"
bring "reduce"
bring "keys"
bring "first"
bring "for-each"
bring "filter"
bring "size"
bring "find-all"
bring "is"
bring "concat"
bring "find-all-indices"
bring "find"
bring "every"
bring "equal"
bring "values"
bring "entries"
